# To build: docker build -f Dockerfile.dev.client -t laudspeaker-ui:latest .
# To run: docker run -it -p 3000:3000 --rm laudspeaker-ui:latest 
FROM node:16 as build
WORKDIR /app
ENV REACT_APP_API_BASE_URL http://localhost:3001
ENV REACT_APP_POSTHOG_HOST https://app.posthog.com
ENV REACT_APP_POSTHOG_KEY phc_MvypYfRDuzzcwISCM9x7hcb5pMthxHA2aF8pJFjoWCY
ENV PATH /app/node_modules/.bin:$PATH
COPY ./packages/client/package.json /app/
COPY ./package-lock.json /app/
RUN npm install --legacy-peer-deps
COPY . /app
RUN npm run format:client
RUN npm run build:client

# stage 2 - build the final image and copy the react build files
FROM nginx:1.17.8-alpine
COPY --from=build /app/packages/client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.dev.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
