services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
        TZ: Asia/Manila
    #   - REDIS_REPLICATION_MODE=master
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    #   interval: 50s
    #   timeout: 2s
    #   retries: 20
    networks:
      - laudspeaker_default
    volumes:
      - ./redis_data:/data

  laudspeaker_pgres:
    image: postgres:14.4-alpine
    hostname: postgres
    container_name: laudspeaker_pgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: laudspeaker
      TZ: Asia/Manila
    ports:
      - "5431:5432"
    restart: unless-stopped
    networks:
      - laudspeaker_default
    volumes:
      - ./laudspeaker_metadata:/var/lib/postgresql/data
    

  mongo:
    image: "mongo:latest"
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: "--bind_ip_all --replSet rs0"
    environment:
        TZ: Asia/Manila
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - laudspeaker_default
    volumes:
      - ./mongo_data:/data/db

  clickhouse:
    hostname: clickhouse
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - TZ=Asia/Manila
    networks:
      - laudspeaker_default
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse

  #### START kafka related containers
  zoo1:
    image: bitnami/zookeeper:latest
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_SERVERS: zoo1:2888:3888
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Manila
    volumes:
      - ./zookeeper:/bitnami/zookeeper
    networks:
      - laudspeaker_default

  kafka1:
    image: bitnami/kafka:3.6.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29092:29092"
      - "9092:9092"
    healthcheck:
      test: kafka-cluster.sh cluster-id --bootstrap-server kafka1:19092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://kafka1:29092,DEV://kafka1:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://kafka1:29092,DEV://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DEV:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_TLS_CLIENT_AUTH: none
      ALLOW_PLAINTEXT_LISTENER: "yes"
      TZ: Asia/Manila
    depends_on:
      - zoo1
    networks:
      - laudspeaker_default
    volumes:
      - ./kafka:/bitnami/kafka

  #### END kafka related containers

  #### START kafka connect related containers
  kafka-connect1:
    image: bitnami/kafka:latest
    hostname: kafka-connect1
    container_name: kafka-connect1
    environment:
      TZ: Asia/Manila
    healthcheck:
      test: ["CMD", "curl", "localhost:8083"]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "8083:8083"
    volumes:
      - ./local-env/kafkaconnect:/opt/bitnami/kafka-connect
    depends_on:
      kafka1:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - bash
      - -c
      - /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka-connect/connect.properties
  #### END kafka connect related containers
 
  kafka-gui:
    container_name: kafka-gui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8081
    environment:
      KAFKA_CLUSTERS_0_NAME: laudspeaker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect1:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      DYNAMIC_CONFIG_ENABLED: "true"
      TZ: Asia/Manila
    networks:
      - laudspeaker_default
   
  init-environment:
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-environment
    depends_on:
      mongo:
        condition: service_healthy
      kafka1:
        condition: service_started
      clickhouse:
        condition: service_healthy
      kafka-connect1:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "environment"

  minio:
    image: quay.io/minio/minio
    command: "server /data --console-address :9123"
    ports:
      - "9123:9123"
      - "9002:9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: storage@dmin20SS
      TZ: Asia/Manila
    container_name: minio
    networks:
      - laudspeaker_default
    volumes:
      - ./minio_data:/data

  ping-server:
    image: jaredhanson11/ping-server:latest
    container_name: ping-server
    ports:
      - "8555:8555"
    environment:
      PORT: 8555
      TZ: Asia/Manila
    networks:
      - laudspeaker_default
    
  minio-createbuckets:
    image: minio/mc
    # profiles:
    #   - "testing"
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 admin storage@dmin20SS;
      /usr/bin/mc mb minio/$$MINIO_CUSTOMERS_IMPORT_BUCKET;
      /usr/bin/mc mb minio/$$MINIO_BUCKET;
      exit 0;
      "
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  laudspeaker:
    # profiles:
    #   - "testing"
    image: laudspeaker:latest
    container_name: laudspeaker
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8084"]
      interval: 5s
      timeout: 30s
      retries: 20
    depends_on:
      init-environment:
        condition: service_completed_successfully
      minio-createbuckets:
        condition: service_completed_successfully
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  init-connectors:
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-connectors
    environment:
      TZ: Asia/Manila
    profiles:
      - testing
    depends_on:
      laudspeaker:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "connectors"

  redis-gui:
    container_name: redis-gui
    image: redis/redisinsight:latest
    profiles:
      - gui
    ports:
      - 8091:5540
    environment:
      TZ: Asia/Manila
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5540/healthcheck || exit 1
    networks:
      - laudspeaker_default

  init-guis:
    profiles:
      - gui
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-gui
    depends_on:
      redis-gui:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "guis"

networks:
  laudspeaker_default:
    driver: bridge
    name: laudspeaker_default

volumes:
  redis_data:
  laudspeaker_metadata:
  mongo_data:
  minio_data:
  clickhouse_data:
  kafka:
  zookeeper: